name: Merge Comment Reminders
description: Pulls flagged comments from edited files and comments them on your PRs
branding:
  icon: check-square
  color: purple
inputs:
  token:
    description: 'Github Token'
    required: true
  repository:
    description: 'The Github Repository'
    required: true
  issueNumber:
    description: 'Issue Number'
    required: true
  baseSha:
    description: 'Base Branch'
    required: true
    default: 'origin/main'
  headSha:
    description: 'PR SHA'
    required: true
    default: 'HEAD'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  merge-comment-reminders-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find merge comments
        id: find-merge-comments
        run: |
          echo "Modified files:"
          files=$(git diff --name-only $INPUT_baseSha $INPUT_headSha)

          if [ -n "$files" ]; then
            echo "$files"
            echo ""

            echo "Modified lines:"
            lines=$(echo "$files" | xargs -r grep -r '[\/\/|#] MERGE:' || echo "")

            if [ -n "$lines" ]; then
              echo "$lines"
              echo ""

              echo "Formatting comments:"
              comments=$(echo "$lines" | sed 's/:.*[\/\/|#] MERGE/`/' | sed 's/^/- [ ] `/' )
              echo "$comments"
              echo ""

              echo 'comments<<EOF' >> $GITHUB_OUTPUT
              echo "$comments" >> $GITHUB_OUTPUT
              echo 'EOF' >> $GITHUB_OUTPUT

            else
              echo "None"
              echo "comments=None" >> "$GITHUB_OUTPUT"
            fi

          else
            echo "None"
            echo "comments=None" >> "$GITHUB_OUTPUT"
          fi

      - name: Find PR comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: $INPUT_issueNumber
          comment-author: "github-actions[bot]"
          body-includes: Merge Reminders

      - name: Update PR comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: $INPUT_token
          repository: $INPUT_repository
          issue-number: $INPUT_issueNumber
          edit-mode: replace
          body: |
            **Merge Reminders**
            ${{ steps.find-merge-comments.outputs.comments }}
          reactions: eyes
