name: Merge Comment Reminders
description: Pulls flagged comments from edited files and comments them on your PRs
branding:
  icon: check-square
  color: purple
inputs:
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    default: ${{ github.token }}
  repository:
    description: "The full name of the repository in which to create or update a comment."
    default: ${{ github.repository }}
  issue-number:
    description: "The number of the issue or pull request in which to create a comment."
    default: ${{ github.event.pull_request.number }}
  base-sha:
    description: "The hash of the base branch."
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  head-sha:
    description: "The hash of the PR branch."
    default: ${{ github.event.pull_request.head.sha }}
  flag:
    description: "The flag to search for in comments."
    default: "Merge:"
  title:
    description: "The title of the comment."
    default: "Merge Reminders"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Find merge comments
      id: find-merge-comments
      shell: bash
      env:
        INPUT_BASE_SHA: ${{ inputs.base-sha }}
        INPUT_HEAD_SHA: ${{ inputs.head-sha }}
        INPUT_FLAG: ${{ inputs.flag }}
      run: main.sh

    - name: Find PR comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-author: "github-actions[bot]"
        body-includes: ${{ inputs.title }}

    - name: Update PR comment
      uses: peter-evans/create-or-update-comment@v4.0.0
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        issue-number: ${{ inputs.issue-number }}
        edit-mode: replace
        body: |
          **${{ inputs.title }}**
          ${{ steps.find-merge-comments.outputs.comments }}
        reactions: eyes
